### ISSUE TITLE
Wheelrate for textArea

### ISSUE THREAD

**Issue by simmihugs** [fjvallarino/monomer#102]
textArea is automatically inside scroll - correct?
now, textArea_ does not have cfg for wheelrate

how can I reach the wheelrate of the implicit scroll of textArea?

**Comment by fjvallarino** [comment]
I'm not sure I understand what you want to do. If your objective is being able to change the `wheelRate` configuration of the `scroll` that wraps your `codeEditor`, you can do it [here (from your repository)](https://github.com/simmihugs/monomer-textArea/blob/main/src/MyTextArea.hs#L264).

That `scrollCfg` list is the regular configuration list you pass to a widget. This means you can add `wheelRate` to it and `scroll` will receive it. If you want to make your widget expose this configuration option, you can add a new field to your configuration record and add the `CmbWheelRate` combinator instance.

**Comment by simmihugs** [comment]
Thanks - with your explanation I was able to find the position in the widget && added a config option
