### ISSUE TITLE
Problems with viewport

### ISSUE THREAD

**Issue by srgtmshnk** [fjvallarino/monomer#110]
Viewports that i am getting from ```wenv ^. L.widgetKeyMap . at (WidgetKey name)``` are always ```Rect {_rX = 0.0, _rY = 0.0, _rW = 0.0, _rH = 0.0}```, Is this a bug or i just miss something? I need a way to make some points inside a big scroll, i give them their ```nodeKey```, and then i am trying to get a viewport of one of them to send it with ScrollTo. Could you please help ?

**Comment by srgtmshnk** [comment]
Awesome! Thank you so much. ```The widgetKeyMap property of WidgetEnv should not have the complete WidgetNodeInfo structure,``` was the problem.

**Comment by fjvallarino** [comment]
Great! I'll close the issue, then. Please re-open if needed. Thanks!
