### ISSUE TITLE
Issue using some container widgets

### ISSUE THREAD

**Issue by monawasensei** [fjvallarino/monomer#112]
I could be totally off base but I am not able to use some container widgets like `box` and `hsplit` in a definition like `box . label $ "foo"`,
 due to this warning:
```No instance for (Typeable s) arising from a use of ‘box’```
I am unable to use `box` with any widget that I tried, aliasing the box function `box' = box` showed the same warning in the definition so it doesn't appear only when applying `box` to other widgets.

I wrote some aliases for label and box:
```
_label :: (Typeable s, Typeable e) => Text -> WidgetNode s e
_label = label

_box :: (Typeable s, Typeable e) => WidgetNode s e -> WidgetNode s e
_box = box

__box :: (WidgetModel s, WidgetEvent e) => WidgetNode s e -> WidgetNode s e
__box = box

_t :: (Typeable s, Typeable e) => Text -> WidgetNode s e
_t = _box . _label
```
And this definition of `_box` and `__box` does not show the warning itself but I am still unable to apply it to either `label` or `_label`, though the definition `_t` shows no warning until it is applied to some Text.
Also tried reverting from monomer-1.3.0.0 to monomer-1.2.0.0 but had the same issue. This may be kind of a noob Haskell problem and not related to Monomer at all so I apologize if this is not worth a ticket.

**Comment by fjvallarino** [comment]
Hi @monawasensei!

If you have a complete example, even something like the default Main.hs file with enough changes to reproduce the problem, I can take a look.

Does the same happen if you use `vstack`, for example?

**Comment by monawasensei** [comment]
Thanks for the reply! I've been trying to reproduce this in the sample Main.hs from the tutorial but I can't. I've managed to reproduce the exact set of packages used in my project in the tutorial project but the issue is not appearing there, only in my other project. I've tried deleting my package store and re-installing everything and that did not resolve the problem. Really kind of stumped on how to reproduce this to be honest with you. I've tried using box in the Main module of my project that is seeing that issue and it works too.

Okay I've found a way to reproduce this and it probably gives a good hint as to why it's happening that I am unaware of. The issue does not appear when I use `box` in my Main module but I have a separate module, Node.Base where I am defining the WidgetNodes I'm using. I can provide a sample cabal project I believe should reproduce this for you. In the meantime, using Tutorial01_Basics.hs as Main.hs you might be able to see this. If you use a box in Main.hs it will work but if you have a module structure like:

app/
---- Main.hs
---- Node/
--------Base.hs

where Base.hs is
```
module Node.Base () where

import Monomer

t = box . label
```

You should be able to see this error.

```
app/Node/Base.hs:5:5: error:
    • No instance for (base-4.13.0.0:Data.Typeable.Internal.Typeable
                         s0)
        arising from a use of ‘box’
    • In the first argument of ‘(.)’, namely ‘box’
      In the expression: box . label
      In an equation for ‘t’: t = box . label
```

**Comment by monawasensei** [comment]
And by the way, vstack and hstack both work for me. I think the problem containers I have are the ones where the function signatures are parameterized with either (WidgetModel s) or (WidgetEvent e).
like this:
```
box :: (WidgetModel s, WidgetEvent e) => WidgetNode s e -> WidgetNode s e
```
or
```
hsplit :: WidgetEvent e => (WidgetNode s e, WidgetNode s e) -> WidgetNode s e
```
and neither label nor the stacks have those parameterizations like
```
label :: Text -> WidgetNode s e
```
and they both work without issue.

**Comment by monawasensei** [comment]
[monomer-issue.tar.gz](https://github.com/fjvallarino/monomer/files/8421735/monomer-issue.tar.gz)
Here is an archive of a cabal project that should reproduce this issue

**Comment by fjvallarino** [comment]
I tested the `Node.Base` example (not the tar.gz one), and this modified version compiles:

```haskell
module Node.Base () where

import Data.Text
import Monomer

t :: (WidgetModel s, WidgetEvent e) => Text -> WidgetNode s e
t = box . label
```

This works because it satisfies the requirements of the `box` function: it expects to receive a `WidgetNode` whose type arguments are of type `WidgetModel` for s, and type `WidgetEvent` for e (both `WidgetModel` and `WidgetType` are aliases of `Typeable`). Since, in this case, we're being explicit in the type signature, everything works fine. 

Alternatively, you can omit the type signature as long as you use the `t` function anywhere in your widget tree (and it resides in the same module). In that scenario, GHC is able to infer the type of `t` and it will also work.

```haskell
t = box . label

buildUI
  :: WidgetEnv AppModel AppEvent
  -> AppModel
  -> WidgetNode AppModel AppEvent
buildUI wenv model = widgetTree where
  widgetTree = vstack [
      label "Hello world",
      t "Test"
  ]
```

In any other situation, GHC can't be sure that `s` and `e` satisfy the requirements imposed by `box` and gives you a compilation error.

**Comment by monawasensei** [comment]
```
(WidgetModel s, WidgetEvent e) =>
```
Was exactly what I was missing from my WidgetNode definition. Adding that to each of my definitions fixed the problem, simple fix lol. Thanks so much! I like this lib a lot, please keep it up!
