### ISSUE TITLE
How to render images

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#121]
Is there a way to render images or even videos from within monomer?

**Comment by toku-sa-n** [comment]
You can use the [image](https://hackage.haskell.org/package/monomer/docs/Monomer-Widgets-Singles-Image.html) widget for rendering images. I'm not sure monomer can render videos.

**Comment by prolic** [comment]
Thanks @toku-sa-n - must have missed it, stupid me :)

**Comment by fjvallarino** [comment]
Hi @prolic! Monomer indeed supports images through the [image](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/04-tasks.md#image) widget. There is no support for video at the time; I plan to add support for gifs as a first step in the future.

Regarding the image widget, it's important to note that it supports the styling properties of all the other widgets. For example, if you set `width`/`height` to 100 and `radius` to 50, you can get an image cropped by a circle.

Take a look at the tutorials; there is an introduction to all the major widgets you can use.

**Comment by prolic** [comment]
Thanks @fjvallarino
