### ISSUE TITLE
Right aligned text moving when getting longer

### ISSUE THREAD

**Issue by sproott** [fjvallarino/monomer#124]
I've noticed this happening with JetBrains Mono, it doesn't happen with the default Roboto font. The longer the label for right-aligned text gets, the more the text moves to the right. Could it be a problem with some font calculation?

[Example](https://github.com/sproott/monomer-right-align-problem)

![image](https://user-images.githubusercontent.com/46423131/163770393-6ae681e1-a273-470d-b4bf-5d26d40a2d80.png)

![image](https://user-images.githubusercontent.com/46423131/163770424-7fcb84ae-a4af-431d-a3d5-e9cb97138500.png)

**Comment by fjvallarino** [comment]
There was indeed a problem, tightly related to another issue I could not fix at the time and which had a temporary workaround. I think the underlying problem is now solved.

You can test by modifying your `stack.yaml` to point to:

```yaml
- git: https://github.com/fjvallarino/monomer
  commit: 418d6ddc697118fc727628e1c5b2f41114c53689
```

**Comment by sproott** [comment]
The PR indeed fixed the problem.

**Comment by fjvallarino** [comment]
Great! I just merged to main. I'll close the issue. Please re-open or create a new one if needed. Thanks!
