### ISSUE TITLE
Terminal/std_out control

### ISSUE THREAD

**Issue by MilesLitteral** [fjvallarino/monomer#126]
Hey again, thanks for all the great work and effort that has gone into this library It has been very helpful and a pleasure to utilize; I was wondering if it was possible, via utility function or otherwise, to put text to the Terminal? As I understand Monomer, and SDL2 use the std_out. Is there anyway to interact with the same pipe that monomer itself is using to, say, output a statement?

Thanks for all your help!

**Comment by fjvallarino** [comment]
Hi @MilesLitteral!

To output text to the console you can use a `Task`, since it receives an `IO` action, and use any of the regular output functions you would use in console programs. For example:

```haskell
newtype AppModel = AppModel {
  _clickCount :: Int
} deriving (Eq, Show)

data AppEvent
  = AppInit
  | AppIgnore
  | AppIncrease
  | AppPrint
  deriving (Eq, Show)

makeLenses 'AppModel

buildUI
  :: WidgetEnv AppModel AppEvent
  -> AppModel
  -> WidgetNode AppModel AppEvent
buildUI wenv model = widgetTree where
  widgetTree = vstack [
      label "Hello world",
      spacer,
      hstack [
        label $ "Click count: " <> showt (model ^. clickCount),
        spacer,
        button "Increase count" AppIncrease
      ]
    ] `styleBasic` [padding 10]

handleEvent
  :: WidgetEnv AppModel AppEvent
  -> WidgetNode AppModel AppEvent
  -> AppModel
  -> AppEvent
  -> [AppEventResponse AppModel AppEvent]
handleEvent wenv node model evt = case evt of
  AppInit -> []
  AppIgnore -> []
  AppIncrease -> [
      Model (model & clickCount +~ 1),
      Event AppPrint
    ]
  AppPrint -> [
      Task $ do
        putStrLn $ "Count is now: " ++ show (model ^. clickCount)
        return AppIgnore
    ]
```

It is also possible to request a `Task` to be run in `AppIncrease`; I just split them to avoid confusion with what to model contains (until `handleEvent` is called again, the `model` variable will still point to the non-updated value).

**Comment by fjvallarino** [comment]
I'll close the issue for now. If you have any other questions, please re-open it or create a new one. Thanks!

**Comment by MilesLitteral** [comment]
Sorry I'd forgotten to submit my comment thanks again for all your help :)

**Comment by fjvallarino** [comment]
Just in case you are using Windows and are still having problems with outputting text to the console, I saw this issue on SDL2's repository which may be related: https://github.com/haskell-game/sdl2/issues/86.

The fix seems to require adding this to your `package.yaml` (copied from this [PR](https://github.com/expipiplus1/vulkan/commit/d506a3d0c07df4bd732af22d16d97faca6dd243a) mentioned in the issue):

```yaml
when:
  - condition: os(windows)
    ghc-options: -optl-mconsole
```
