### ISSUE TITLE
Problems in the doc (probably trivial)

### ISSUE THREAD

**Issue by MuhammedZakir** [fjvallarino/monomer#139]
1. From https://github.com/fjvallarino/monomer/issues/136#issuecomment-1120147291:
> Out of topic: in the Monomer lens utils, it would be nice if you could add a one-liner description to each function. For example, when I read `Monomer.Graphics.Lens`, I was confused when I saw the `a` function. I guessed it is to get the alpha value after looking at other functions in that module. The same happened when I read the doc for the _widget-lens-util_ module. I could open a PR, but that will take a long time as I will need to familiarize with all these first.

2. **Not Found**: https://hackage.haskell.org/package/monomer-1.4.0.0/docs/Accept.html
    - mentioned - e.g. https://hackage.haskell.org/package/monomer-1.4.0.0/docs/Monomer-Widgets-Singles-Button.html#g:2

**Comment by fjvallarino** [comment]
Regarding point 1, I can't do anything at this point. The lenses are generated with `TemplateHaskell` by the `lens` library, and that extension has a limitation mentioned in [this issue](https://github.com/ekmett/lens/issues/614). Luckily, it seems it will be possible in the future when that GHC version becomes available in Hackage.

In general, I recommend checking the documentation of the target type you are interested in. Lenses names are derived from the names of the fields by stripping the prefix; you can get to the documentation based on that logic.

**Comment by MuhammedZakir** [comment]
3. **Not found**: https://hackage.haskell.org/package/monomer-1.4.0.0/docs/WidgetRequest.html.
    - mentioned: https://hackage.haskell.org/package/monomer-1.4.0.0/docs/Monomer-Core-WidgetTypes.html#t:WindowRequest

**Comment by fjvallarino** [comment]
Fixed in this PR: https://github.com/fjvallarino/monomer/pull/145.

This will be available in Hackage when the next version is released (it will take a few weeks). I interleaved new features between the commits containing Haddock fixes, and pushing an update now would show things not available in 1.4.0.0.

**Comment by fjvallarino** [comment]
Since the fix is already in main, I'll close the issue.

Also, a new release has been pushed to Hackage, and the documentation should be ready at some point today (it takes a few hours)
