### ISSUE TITLE
[Bug] Changing cursor using `styleHover` for a button sets that cursor for all buttons

### ISSUE THREAD

**Issue by MuhammedZakir** [fjvallarino/monomer#141]
Example:

```haskell
vstack [
  flip button ButtonClick ("Click count: " <> showt (model ^. clickCount)
    `styleHover` [cursorHand]
, spacer
, flip button ButtonClick ("Click count: " <> showt (model ^. clickCount)
]
```

Happens even if a different `onClick` event is used.

**Comment by fjvallarino** [comment]
By default, buttons have a hand cursor on hover (defined in the base theme). Considering this, setting `cursorHand` does not cause an effect (both buttons already have it). You can try using `cursorInvalid`, or any of the other cursors, to validate it works as expected.

**Comment by MuhammedZakir** [comment]
That is indeed the case. I don't know why I did that. Sorry for the noise.
