### ISSUE TITLE
"About to destroyWindow" to stderr

### ISSUE THREAD

**Issue by monawasensei** [fjvallarino/monomer#164]
This is a minor thing but I was just curious.
Given that the text when starting a monomer application is printed to stderr, why is the text on closing a monomer application printed to stdout?
I see that it's set in Monomer.Main.Platform.destroySDLWindow.
Would you have any objections to a PR changing it to stderr?

**Comment by fjvallarino** [comment]
Hi @monawasensei!

The reason is that I did not pay attention to the fact that those messages were sent to different handles (that line is probably there since the very beginning of the project). I'm fine with changing it to `stderr` or even removing the line!

**Comment by fjvallarino** [comment]
I just pushed a PR that removes the exit message and switches all log messages (diagnostics and errors) to stderr.
