### ISSUE TITLE
Label widget does not resize when the style is changed (except for the text style)

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#168]
This seems like a bug to me, or at least surprising behaviour.

To reproduce:

1. Run `stack run` inside the attached modified-monomer-starter-project: [monomer-label-merge-bug.zip](https://github.com/fjvallarino/monomer/files/8884669/monomer-label-merge-bug.zip)
2. Click the "Increase count" button.
3. Observe the issue:
   - Expected behaviour: the "Hello World" label immediately increases in height.
   - Actual behaviour: the label does not change height until the mouse moves over it.

The issue seems to be related to the Label merge function not checking the entire style value for changes -- it only checks the text style: https://github.com/fjvallarino/monomer/blob/main/src/Monomer/Widgets/Singles/Label.hs#L225

Cheers!

**Comment by fjvallarino** [comment]
Hi @Dretch!

This should be fixed in the PR I just submitted. I tested locally and it seems to work as expected.

**Comment by fjvallarino** [comment]
The PR has been merged to master; I'll close the PR now. Thanks for reporting!
