### ISSUE TITLE
Missing 'freetype2' for windows build

### ISSUE THREAD

**Issue by JD95** [fjvallarino/monomer#17]
nanovg complained about missing freetype2, but fixed with 
```
stack exec -- pacman -S mingw-w64-x86_64-freetype
```
Not sure if I was missing something or the instructions on the readme where incomplete

**Comment by fjvallarino** [comment]
@JD95 I hadn't realized the flag was missing in the `monomer-starter` project, which caused the issue you reported. That project has now been fixed.

After an upgrade to Stackage's latest LTS, the Windows build command is now the same as in the other platforms. The Setup docs have been updated to reflect this. If you pull the latest version and build again, it should work fine.

In case you want to test from scratch (to make sure Freetype is indeed not needed), you will need to:

- Remove .stack-work on the project's directory.
- Remove C:\sr (the default location where Stack usually puts its files, or the correct location if you customized it).
- Remove %LOCALAPPDATA%\Programs\stack (this is where the MinGW that is used by Stack is installed).

After these steps, you can follow the now updated Setup docs for a clean install.

Thanks!

**Comment by fjvallarino** [comment]
@JD95 I'll close this issue for the time being. If you find any problems or have other questions, don't hesitate to re-open it or create a new one. Thanks!
