### ISSUE TITLE
glew missing

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#174]
Someone cloned my project and ran `stack run` - but still couldn't make it work. The error output is this:
```
nanovg           > configure
nanovg           > Configuring nanovg-0.8.0.0...
nanovg           > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The pkg-config package 'glew' is
nanovg           > required but it could not be found.
nanovg           > 
```

Since I never ran into this before, maybe you have an idea what is missing?

**Comment by fjvallarino** [comment]
They need to have it installed in their system. The way to install the library for each OS is shown [here](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md#libraries-sdl2-and-glew)

**Comment by prolic** [comment]
Thanks, my bad then.
