### ISSUE TITLE
Add shared model

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#183]
Since this library is based on the ideas of the Elm Architecture, I wonder if it makes sense to also add a shared model. See https://www.elm-spa.dev/guide/05-shared-state.

The idea is, that a lot of widgets have its own model, but also need to consume / produce data for a shared model, that all widgets have access to. This might be a BC, not sure if this can be done without affecting changes further down the road, but at least as a default the shared model can be the empty tuple, in case nothing is provided.

**Comment by fjvallarino** [comment]
I don't think this is part of the standard Elm Architecture; it's an elm-spa feature to handle data sharing between routes (one possible solution to that need).

I prefer to restrict access to data in a hierarchical way. If a widget needs a piece of data, some of its ancestors should have that data as part of its model and pass it down. If all the widgets need this data, it should be in the top-level model.

**Comment by prolic** [comment]
I see, thanks.
