### ISSUE TITLE
How to create statically linked binaries?

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#195]
I tried this in my stack.yaml:

```
    extra-libraries:
    - GLEW
    - GLU
    - GL
    - SDL2
```

```
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    - -static
    - -fPIC
    - -optl-static
    - -optl-pthread
```

However I run into problems, see https://pastebin.com/pTq6SeSz

Any suggestions?

**Comment by prolic** [comment]
Okay, I managed to get something done using `AppImage`. Will try to create some binaries for windows next.
I may write a blog post once I have everything together.

**Comment by fjvallarino** [comment]
Awesome!

Could you share your blog post when you publish it? Thanks!

**Comment by prolic** [comment]
@fjvallarino sorry took a while had some stuff going on...

https://www.sasaprolic.com/2022/11/statically-linked-binaries-with-haskell.html
