### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ezoerner** [fjvallarino/monomer#197]
Thought I'd try monomer out and build the examples, but I'm getting a build failure using `stack build`:

```nanovg         > Configuring nanovg-0.8.0.0...
nanovg         > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The program 'pkg-config' version
nanovg         > >=0.9.0 is required but it could not be found.
nanovg         > 
sdl2           > configure
sdl2           > Configuring sdl2-2.5.3.0...
sdl2           > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The program 'pkg-config' version
sdl2           > >=0.9.0 is required but it could not be found.
sdl2           >       
```

Is there something wrong with my environment?

Using Stack 2.7.5

Installed with brew on macOS:
sdl2: stable 2.0.22 (bottled), HEAD
glew: stable 2.2.0 (bottled), HEAD

**Comment by ezoerner** [comment]
Fixed by doing:
`brew reinstall sdl2 pkg-config`

So,  the environment setup guide in this project should be changed to read:
`brew install sdl2 pkg-config`

**Comment by fjvallarino** [comment]
Hi @ezoerner!

I had the impression `pkg-config` was available by default with Homebrew. Most likely some package I installed added it as a dependency.

I just merged to main an [update to the setup page](https://github.com/fjvallarino/monomer/pull/198).

Thanks for reporting!

**Comment by fjvallarino** [comment]
I'll close the issue for the time being. Please re-open or create a new one if needed. Thanks!
