### ISSUE TITLE
(Question) Mouse Hover Events

### ISSUE THREAD

**Issue by MilesLitteral** [fjvallarino/monomer#200]
Hello @fjvallarino 

I was curious if Monomer had out of the box support for MouseHover (or MouseOver) events similar to Keystroke, I was looking through hackage and tutorials but I feel maybe I missed something?

**Comment by MuhammedZakir** [comment]
Use `onEnter` and `onLeave` event handlers along with `box_`. See tutorial 4 (Tasks) for an example.

**Comment by MilesLitteral** [comment]
Thanks!

**Comment by fjvallarino** [comment]
I think this issue can be closed. Please re-open if needed. Thanks!
