### ISSUE TITLE
Feature request/suggestion: alert shadows

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#203]
Basically I think shadows look nice.

### Without shadows (current)

![without-shadow](https://user-images.githubusercontent.com/1428731/189493694-ee4d9d45-67d9-477d-9d48-c444c4bfe213.png)

### With shadows (proposed)

![with-shadow](https://user-images.githubusercontent.com/1428731/189493710-cbcd9286-4a71-44b5-af21-b6cc33221cb3.png)

If this is something you would be willing to add to Monomer then I have a half-finished branch that I would be happy to make production-ready: https://github.com/Dretch/monomer/tree/alert-shadows ... if not, then fair enough :smile:

**Comment by fjvallarino** [comment]
Hi @Dretch!

Absolutely, I'm interested in the PR! I have not added the `boxGradient` yet mainly to avoid tying the code too much to NanoVG, but I don't think replicating what that function does would be too complex in case we ever move away from using that library.

Regarding how the shadow is displayed, an alternative is to have it visible only on two of the borders, so it gives a feeling that the content is popping out of the screen (example attached):

<img width="210" alt="image" src="https://user-images.githubusercontent.com/6565497/189503603-1b9c2db8-6503-4e56-87c8-579bb283e765.png">

**Comment by fjvallarino** [comment]
@Dretch this has been merged. I'll close the issue now. Thanks!
