### ISSUE TITLE
Using sum types in Model

### ISSUE THREAD

**Issue by Soupstraw** [fjvallarino/monomer#206]
I'm trying to make a text-based game using monomer, but I'm struggling a bit with making different views. For example, when the app is launched, I want the user to be in the main menu view. From there they can click on a button to move into the game view or the options view. The way I would implement this is to define the app model as a sum type like this:
```
data AppModel
  = MainMenuView MainMenuModel
  | GameView GameModel
  | OptionsView OptionsModel
```
Now when I want to add fields to the options view, the most convenient way to do this would be to use lenses, but since `AppModel` is a sum type, I only have access to a prism, which is not accepted by, say, `numericField`. 

I also considered adding a data kind parameter to the app model so that I can keep track which view I'm in on the type level, but then I get stuck whenever I need to switch from one view to another, because the `EventHandler` can only switch to a new model if it has the exact same type.

So my question is, what's the monomer way to make apps with multiple views?

**Comment by Soupstraw** [comment]
Ahh, I wasn't aware of `singular`, I'll try it out.

**Comment by fjvallarino** [comment]
@Soupstraw I'll close the issue for now. Please re-open if needed or create a new one. Thanks!
