### ISSUE TITLE
[Question] How to adjust window title after startApp?

### ISSUE THREAD

**Issue by dimsuz** [fjvallarino/monomer#213]
It seems that the only way to set window title is to pass it with `config` to `startApp`, but is there a way to change it later?

Use case: app that has a list of items and then opening some item changes whole window contents to display item details and title can reflect which item is currently viewed. For example viewing book details could change window title to the book title.

**Comment by fjvallarino** [comment]
The top-level Application is itself a [Composite](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/06-composite.md), and besides user-events they have the option of [returning other things](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/06-composite.md#widget-requests). One of them, [WidgetRequest](https://hackage.haskell.org/package/monomer-1.5.0.0/docs/Monomer-Core-WidgetTypes.html#t:WidgetRequest)'s, give you the ability to do what you need. In your case you're interested in the `UpdateWindow` request, that receives a [WindowRequest](https://hackage.haskell.org/package/monomer-1.5.0.0/docs/Monomer-Core-WidgetTypes.html#t:WindowRequest).

The code would look similar to:
```haskell
handleEvent wenv node model evt = case evt of
  ...
  ChangeTitleEvent -> [ Request (UpdateWindow (WindowSetTitle "New title")) ]
  ...
```

**Comment by dimsuz** [comment]
Oh, I missed that it's also a `Composite`. Thank you, I guess I really should read tutorials more thoroughly.

A side question I had yesterday: do you think it is sensible to split `AppModel` into multiple sub-models in cases where application consists of multiple distinct (and complex) "sub-screens", for example:

```haskell
data AppModel = BookList BookListModel | BookDetails BookModel | ServiceLogin CredentialsModel

data BookListModel = { books: [Book], ... }
data BookDetals { book: Book, checkbox1: Bool, ... }
data CredentialsModel { username: Text, password: Text }
```
and `buildUI` at top-level pattern matches and switches to the corresponding "sub-screen" widget tree as needed.

Or is it preferable to keep everything in a "global" `AppModel` record?
I understand that `monomer` doesn't prescribe any shape for the `AppModel`, but maybe some shape works better than others.

**Comment by fjvallarino** [comment]
Considering you are planning on using a sum type for the model, maybe this issue will be of interest: https://github.com/fjvallarino/monomer/issues/206.

In general, if the different screens are going to be complex and having a separate model and/or events for each of them would make it easier to manage, you can use a Composite for each of them and show them depending on your needs. The code for each of the screens would look like the main application code you currently have.

It's hard do draw a line on when to use a Composite or not. In my opinion the deciding factor is whether having a separate event type will make maintenance easier. On the other hand, you can have a single event type and several handlers you dispatch events to:
```haskell
data EventAInfo = Event1 | Event2
data EventBInfo = Event3 | Event4
data MainEvent = EventA EventAInfo | EventB EventBInfo

handleEvent wenv node model evt = case evt of
  EventA info -> handleEventA info
  EventB info -> handleEventB info
...
```

The `handleEventA` and `handleEventB` don't even need to be in the same module. The same idea applies to the functions that build your UI. 

Improving Composite's documentation is one of the next few things I'm going to work on.

**Comment by dimsuz** [comment]
I will have this in mind, thank you for the detailed answer!
