### ISSUE TITLE
Add a file picker widget

### ISSUE THREAD

**Issue by Soupstraw** [fjvallarino/monomer#214]
It would be great if there was a way to open a file browser to load/save files. What I have in mind is something similar to picture below.

![file picker](https://user-images.githubusercontent.com/6863341/196453463-83a4eaeb-12e6-41d9-8c19-07d9e40946b2.png)

**Comment by fjvallarino** [comment]
Hi @Soupstraw!

There was a PR about this topic, and I did not move forward with merging it because having this functionality requires an additional dependency that may not be required in all cases.

You can see the discussion in this PR, and maybe copy the ideas proposed there for your own project: https://github.com/fjvallarino/monomer/pull/166

I failed to update the documentation as I suggested at the time, but I have not forgotten about it.

**Comment by Soupstraw** [comment]
Ahh, sorry I didn't see that one, I'll take a look.

**Comment by Soupstraw** [comment]
The PR seems to use `tinyfiledialogs`, which opens an external file browser. I'm thinking it would probably be possible to make a native file browser for Monomer that runs entirely inside the application.

**Comment by fjvallarino** [comment]
Oh, you mean creating a Monomer widget? Sure, it is possible, but I guess it will have limitations. Navigating regular directories and selecting files should be easy, but other integrations like the ones displayed in the attached image (it looks like GTKs file browser) are quite complex and out of scope for the core library (it makes sense for a third party library).

I'll give it a try once I'm done with other active issues. I'm thinking something along the lines of: https://github.com/aiekick/ImGuiFileDialog

**Comment by MilesLitteral** [comment]
> The PR seems to use `tinyfiledialogs`, which opens an external file browser. I'm thinking it would probably be possible to make a native file browser for Monomer that runs entirely inside the application.

Generally speaking the biggest difficulty I ran into with trying to create a widget is trying to get read/write handlers that were platform agnostic. Trying to do so in Linux is relatively easy as there are more than a few libraries available that grant such handlers painlessly, it's trying to do so in other OS that I found tricky, as well as the boilerplate that went with it that felt like more work than it was worth hence I relegated to opening the file browser of the OS Monomer was running on. It's definitely possible you will just have to do a lot of work the OS does for the user when requesting the relevant information as is

**Comment by Soupstraw** [comment]
Yeah, makes sense. I think it would make a lot of sense to have it as a separate library then instead, no point in adding complex dependencies to this package just for this one feature.
