### ISSUE TITLE
Infinite resize loop with multiline labels (possible bug)

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#225]
I have found some unexpected behaviour. It might be a bug or I might just be doing things wrong :wink: 

For context, I am looking at changing monomer-hagrid so it only creates widgets for visible (or nearly visible) rows, to improve performance. This is tricky because rows can have arbitrary height, so it is not trivial to know how many rows will be needed to cover the visible window.

Currently the solution I have implemented does a loop of 1. add some rows to the model; 2. trigger a resize (so the rows attain their correct height; 3. If the visible window is covered, finish, otherwise go to (1).

This mostly works ok, but I have discovered an issue with multiline labels where adding a label, then resizing, then adding another label and resizing again (all in the same frame) can trigger the labels to keep requesting a resize in an infinite loop.

## To Reproduce

1. `stack run` this modified hello-world app: [monomer-label-resize-loop.zip](https://github.com/fjvallarino/monomer/files/9944037/monomer-label-resize-loop.zip)
2. Click the "Add Label" button.
3. Observe that the app has frozen: it is now in an infinite loop.

## Possible Explanations

Firstly, I might just be doing something silly with custom widgets here. I don't understand the Monomer internals deeply, so might have missed something (or misread the docs, or something).

On the other hand, there is some code here that is related (according to my debugging): https://github.com/fjvallarino/monomer/blob/d1ddcc2d40a6151d50fca33dbca1302fa7b2e19b/src/Monomer/Widgets/Singles/Label.hs#L290 ... at runtime, in the demo, there are two labels, and on each iteration of the infinite loop an alternating label requests a resize: the timestamps remain the same but `needsSndResize` flip-flops and rather than just doing a second resize, each label does an infinite number of resizes. It is not entirely clear how to fix this, at the moment, though.

**Comment by fjvallarino** [comment]
This is definitely an issue! I just pushed a branch with a potencial fix. The infinite loop in your example is gone, but I guess your use case is more complex.

You can test the fix by pointing your `stack.yaml` to:

```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: d9308b794771ab81061bade19d7534adfcfd5e45
```

Let me know if it works for you and it does not cause unexpected issues. Thanks!

**Comment by fjvallarino** [comment]
@Dretch curious: does this happen while resizing the window only? Maybe I can replicate it with a bit more detail.

**Comment by fjvallarino** [comment]
@Dretch sorry for the long delay. Just to be sure: do you think the PR is good to merge, then? 

By the way, I've been working on some improvements to the development workflow. Maybe you find it useful: https://github.com/fjvallarino/monomer/pull/239

**Comment by fjvallarino** [comment]
The PR has been merged. I'll close the issue now. Please re-open or create a new one if needed. Thanks!
