### ISSUE TITLE
A problem with running examples

### ISSUE THREAD

**Issue by oshyshko** [fjvallarino/monomer#238]
The following steps "Build the examples included with the library" do not work:
https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md#build-the-examples-included-with-the-library

```
$ stack build --flag monomer:examples
$ stack run todo
The following components have 'buildable: False' set in the cabal configuration, and so cannot be targets:
    monomer:exe:todo
To resolve this, either provide flags such that these components are buildable, or only specify buildable targets.
```
Running a binary directly while staying in project directory works:
```
$ .stack-work/dist/x86_64-osx/Cabal-3.6.3.0/build/todo/todo
```

**Comment by ahoro** [comment]
I'm having the same problem on Windows 10.

**Comment by fjvallarino** [comment]
@oshyshko thanks for reporting! I just merged to main a fix to the documentation.
