### ISSUE TITLE
Question about openGL and slippy maps as widgets

### ISSUE THREAD

**Issue by peterjamesward** [fjvallarino/monomer#261]
Looking through monomer and it looks almost perfect for me.
I must just ask two questions so that I don't dig myself a deep hole.

I will need to be able to show (and pan, tilt and zoom) 3D pictures with openGL.
This should be fine, as it's all openGL anyway, but would that be a custom widget?

Similarly, I need "slippy maps" to tile (zoom, pan) a collection of PNGs.
Custom widget, I guess?

Ultimately, hope to achieve something like the current web app shown.
<img width="1483" alt="Screenshot 2023-02-21 at 12 01 05" src="https://user-images.githubusercontent.com/34382358/220339596-233241a4-c7b1-42b4-ba4e-858abe503d44.png">
Map is currently JS (nightmare), 3D view is openGL, profile view is canvas, bottom right is SVG.

-- Peter

**Comment by peterjamesward** [comment]
Ah. I've found your openGL example -- that should help!

**Comment by fjvallarino** [comment]
@peterjamesward I think creating a custom widget is the best option in this case, yes. If you only need 2D, maybe you are fine with the drawing API provided by the library (which in turn uses NanoVG). If one of your maps is tiles based (similar to what some clients of OpenStreetMap do), it will be simpler than going full into OpenGL.

**Comment by fjvallarino** [comment]
I'll close the issue for the time being. Please re-open if needed. Thanks!
