### ISSUE TITLE
Alert contents do not update dynamically

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#265]
The alert widget is implemented internally with a composite, with the widget data set to `WidgetValue ()`. Since this value never changes, the widget view is not updated when the model (or anything outside the model) changes.

Here is a little proof-of-bug: [monomer-alert-updates.tar.gz](https://github.com/fjvallarino/monomer/files/11183764/monomer-alert-updates.tar.gz) -- the label on the widget should be updating continuously, like the label in the background, but it does not.

I'm not sure how to fix this. Maybe alert should accept a `mergeRequired` config option (and pass it directly to the composite constructor)?

**Comment by fjvallarino** [comment]
@Dretch I'll think about it a bit more, but I just pushed a PR that solves the issue. The only problem is it requires your parent model to implement `Eq`; while it is not an extremelely demaning constraint, it's still something extra.

The idea originally was that this modals were for static information, but really it makes sense that they are more flexible (and it would be less surprising for a user who expects the content to update as in the rest of the library).

Your idea of using `mergeRequired` sounds good to avoid the extra constraint.

**Comment by Anteproperispomenon** [comment]
Maybe keep the original version of alert (in addition to the new version), but rename the old version as "static alert" or something like that.

**Comment by fjvallarino** [comment]
@Dretch after thinking about it a bit more, I realized the `Eq` constraint does not add more specificity than what is already requested from the user's model. Composite requires `Eq` to detect model changes and trigger merge when needed, and, considering the Application itself is a Composite, the model already has to implement `Eq`.

That said, if you have a specific use case requiring a separate version without the `Eq` constraint, it's more than welcome. Thanks!

**Comment by fjvallarino** [comment]
@Dretch I'll close the issue for the time being. Please re-open if needed!
