### ISSUE TITLE
Crash on nested startapps?

### ISSUE THREAD

**Issue by liamzee** [fjvallarino/monomer#277]
Access violation in generated code when reading 0x28

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x42d9fffa50 0x7fffafc8d773 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x9fd773
 * 0x42d9fffaa0 0x7fffafcb3ee6 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0xa23ee6
 * 0x42d9fffaf0 0x7fffaf9a66e0 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x7166e0
 * 0x42d9fffb20 0x7fffaf31ac22 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x8ac22
 * 0x42d9fffb90 0x7fffaf966e47 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x6d6e47
 * 0x42d9fffc60 0x7fffafd2bbad C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0xa9bbad
 * 0x42d9fffca0 0x7fffafd2c713 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0xa9c713
 * 0x42d9fffd30 0x7fffaf2cd820 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x3d820
 * 0x42d9fffd70 0x7fffaf875bd4 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8829ad0eb26b3ef6\ig9icd64.dll+0x5e5bd4
 * 0x42d9fffda0 0x7ff81b4c7604 C:\WINDOWS\System32\KERNEL32.DLL+0x17604
 * 0x42d9fffe20 0x7ff81bd226a1 C:\WINDOWS\SYSTEM32\ntdll.dll+0x526a1

Not sure if this is reproducible on non-Windows machines, but here's the relevant code:

```

main :: IO ()
main = startApp defModel handler builder
    [ appFontDef "Regular" "C:/Windows/Fonts/comic.ttf"
    , appTheme darkTheme
--    , appInitEvent InitEvent
    ]


import Monomer

data NullModel = DefaultModel {
    fadeIn :: Bool
    }deriving Eq

defModel = DefaultModel True

data Events = InitEvent | FadeIn | FadeOut | Nest | Null

handler wenv wnd model event = pure $ case event of
    FadeIn  -> Model $ model {fadeIn = True}
    FadeOut -> Model $ model {fadeIn = False}
    Nest    -> Task (main >> pure Null)
    Null    -> Model $ model


builder
  :: WidgetEnv NullModel Events
  -> NullModel
  -> WidgetNode NullModel Events
builder wenv model = nestButton


nestButton = center $ button "spawn new window" Nest

```

**Comment by Deltaspace0** [comment]
@liamzee I tested spawning new window on Ubuntu and got this crash message:
malloc(): unsorted double linked list corrupted
Aborted (core dumped)

Command "stack repl --main-is monomer:exe:dev-test-app" exited unexpectedly with error message: Aborted (core dumped)

**Comment by Deltaspace0** [comment]
Oh, it has been mentioned that multi window is not currently supported here before: https://github.com/fjvallarino/monomer/issues/143#issuecomment-1121953388

**Comment by fjvallarino** [comment]
@liamzee as @Deltaspace0 mentioned, at this point there is no support for multiple OS windows. As mentioned in the linked comment, I'm not against having support for this feature but it's really low in the priorities. While I understand that for certain scenarios and workflows having multiple OS windows is preferrable, the single window model is really flexible and most UIs can be expressed in it.

Regarding the `startApp` function, besides creating the window it also takes care of initializing SDL, so calling it multiple times will most likely cause issues.

**Comment by liamzee** [comment]
Thanks for the information! Might it be useful to note this in the Haddock documentation?
