### ISSUE TITLE
Could you add this package to Stackage?

### ISSUE THREAD

**Issue by toku-sa-n** [fjvallarino/monomer#28]
By adding a package to Stackage, we can use [the online Hoogle](https://hoogle.haskell.org/) to search functions. [Here's the instructions](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by fjvallarino** [comment]
Hi @toku-sa-n! Adding the library to Stackage is one of the following things I will do, but I want to release a couple of bug fixes first.

I will keep you posted.

**Comment by fjvallarino** [comment]
@toku-sa-n this is technically done since the project has been added to Stackage (see this [PR](https://github.com/commercialhaskell/stackage/pull/6260)), but there has not been a Stackage release in the last few days. Once that happens, it will be possible to search on Hoogle.

**Comment by fjvallarino** [comment]
A new Stackage version was released, including the latest version of monomer: https://www.stackage.org/nightly-2021-11-06/package/monomer-1.2.0.0

Hoogle has not yet included the package, and I guess it will remain that way until the current set of nightlies turns into an LTS release.

I'll close the issue for now. If you feel something is missing, please re-open it or create a new one. Thanks!

**Comment by toku-sa-n** [comment]
Thank you!
