### ISSUE TITLE
Difference between a "Message" and an "Event"

### ISSUE THREAD

**Issue by Eisverygoodletter** [fjvallarino/monomer#311]
The 5th tutorial page introduces Producers and it also a `sendMsg` function that seems to send an `Event`.
https://github.com/fjvallarino/monomer/blob/58b08083e3abc5ada70460fb1b12fb6d2abfbcbf/examples/tutorial/Tutorial05_Producers.hs#L64-L69
In the 6th page, this definition is given:
```hs
data EventResponse s e sp ep
  -- Sets the model
  = Model s
  -- Raises an event to itself
  | Event e
  -- Raises an event to its parent
  | Report ep
  -- Sends a Widget Request
  | Request (WidgetRequest s e)
  -- Sets focus on the given key
  | SetFocusOnKey WidgetKey
  -- Moves focus forward/backward, optionally starting from the given key.
  | MoveFocusFromKey (Maybe WidgetKey) FocusDirection
  -- Sends a message to the specified key
  | forall i . Typeable i => Message WidgetKey i
  -- Launches a Task
  | Task (TaskHandler e)
  -- Launches a Producer
  | Producer (ProducerHandler e)
```
Was the `sendMsg` in sending an `Event e`, a `Message WidgetKey i` or something completely unrelated? It has the type
`AppEvent -> IO ()`

Is there a difference between the meanings of "Events" and "Messages" in monomer?

**Comment by Deltaspace0** [comment]
`sendMsg` here accepts `Event` and has nothing to do with `Message WidgetKey i`.

It is rather confusing name of the function which is passed to the producer here, `raiseEvent` would be better instead of `sendMsg` I think.

The difference: Events you raise in app itself or in composites, Messages you send directly to separate widgets.

**Comment by Eisverygoodletter** [comment]
Thanks for the explanation!
Another question about composites and the difference between `Event e` and `Report ep`
From my understanding:

---
In a widget tree like
```

  Some container widget
                |
                |
-----------h-stack ---------------
|                               |
|                               |
compA                          compB
```
where `compA` and `compB` are composite widgets that contain more sub-widgets:
If I create an `Event e` from a `compA`'s `handleEvent`, only widgets in `compA` will observe the event.
If I create a `Report ep` from a `compA`'s `handleEvent`, all parent widgets of `compA` will observe the event but `compB` will be unaware of it.
The types `e` and `ep` can be different and I just have to make sure `compA`'s `ep` matches with the overall App's `e`

---

Is it possible for a parent widget (e.g. `h-stack`) to trigger an event in the child composites without using a Message?

**Comment by Deltaspace0** [comment]
Yeah, your understanding is correct.

From https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/06-composite.md

> Communication between the parent and the composite can work in both ways:

> The parent can provide information to the composite through the model, parameters accepted by the function that creates the composite, or any kind of configuration.

What you can do is update the model in the parent which is connected to the child composite, and then in composite configs do [compositeMergeEvents](https://hackage.haskell.org/package/monomer-1.5.1.0/docs/Monomer-Widgets-Composite.html#v:compositeMergeEvents)

I believe it is only way to trigger an event in the child composite.

You can look at one of my widgets where I use this: https://github.com/Deltaspace0/monomer-widgets/blob/master/src/Monomer/Dragboard.hs

```haskell
compositeMergeEvents $ \_ _ _ _ m _ -> [EventMerge m]
```
So here `EventMerge` is an event inside a child composite, and it triggers when a model updates.

**Comment by Eisverygoodletter** [comment]
Thanks for the explanation!
