### ISSUE TITLE
Haddocks are not generated correctly

### ISSUE THREAD

**Issue by Sorokin-Anton** [fjvallarino/monomer#313]
[README](https://github.com/fjvallarino/monomer?tab=readme-ov-file#haddock) points me to hackage and says I can find haddocks here, but https://hackage.haskell.org/package/monomer has no haddock (all modules are unclickable) 😢 

<img width="663" alt="image" src="https://github.com/fjvallarino/monomer/assets/68074884/997bca43-e9cb-4840-b8a3-25ac10ffe849">

**Comment by fjvallarino** [comment]
@Sorokin-Anton I manually uploaded the documentation, and this should be fixed now.

The SDL2 package is failing its build on Hackage, and the automatic process that generates the documentation is not running.

**Comment by Sorokin-Anton** [comment]
Thanks! Will you create an issue in sdl2 repo?
BTW, is it possible to somehow ensure that you won't forget to upload it manually if you release a new version?
Anyway, looks like the issue can be closed (feel free to do it)

**Comment by fjvallarino** [comment]
@Sorokin-Anton I think they are aware, it's been happening for a while.

To be honest I did notice the failure, but I had forgotten I could upload the documentation manually; I even have a script that takes care of most of the steps, except uploading which needs to be done manually. I'll try my best not to forget, but creating an issue to let me know about it if I do is a good idea.
