### ISSUE TITLE
Use of `trace` with Monomer on Windows Machines

### ISSUE THREAD

**Issue by ulfur-einn** [fjvallarino/monomer#320]
Currently the use of `trace` from debug.trace is does not output any result when in use with Monomer on Windows. It works just fine on Linux, but it outputs nothing to the terminal on Windows. It still builds just fine, just outputs no text. 
`error` works on both, but on Windows it manifests as a dialogue box.

I'm not sure if this was intentional, but trace would be a very helpful tool if it were available.

**Comment by fjvallarino** [comment]
Hi @ulfur-einn!

Maybe the discussion in this issue is helpful: https://github.com/fjvallarino/monomer/issues/207

**Comment by ulfur-einn** [comment]
Thank you, the inclusion of `-optl-mconsole` in my cabal file worked. 

I appreciate your help!
