### ISSUE TITLE
How to make monomer default to Wayland instead of X11?

### ISSUE THREAD

**Issue by gnull** [fjvallarino/monomer#52]
I've just built the [Basics Tutorial](https://github.com/fjvallarino/monomer/blob/main/examples/tutorial/Tutorial01_Basics.hs) using stack and ran in on my Arch, which has both Wayland and X11 (through XWayland) available. And it used XWayland by default (I checked using `xeyes`). How do I ensure that my programs use Wayland for drawing windows whenever it's available?

Ivan

**Comment by fjvallarino** [comment]
Hi @gnull! Monomer uses SDL2 for setting up windows and OpenGL contexts. Checking on SDL2's repository, it seems they are working on using Wayland when available, but there are some issues and it's why it's still not the default.

- Main discussion:
  - https://github.com/libsdl-org/SDL/issues/2710
- Not yet merged patch to default to Wayland
  - https://github.com/libsdl-org/SDL/pull/4306 

This article mentions exporting `SDL_VIDEODRIVER=wayland` from the shell before running your application as a workaround: https://www.phoronix.com/scan.php?page=news_item&px=SDL-Wayland-State-2021

**Comment by gnull** [comment]
Ah, I see. Thank you for your reply!

I already tried the `SDL_VIDEODRIVER=wayland` and it made the program crash (which is normal I guess, since SDL2's support for Wayland is not complete yet).

I'll close the issue since it's in the hands of SDL2 devs now.

**Comment by 1ace** [comment]
@gnull please have a look through https://github.com/libsdl-org/SDL/issues to see if someone's already posted the crash you are seeing, and create a new issue if not :slightly_smiling_face: 

People like you trying wayland before it's the default is exactly what is needed to fix the issues so that it can become the default, but for that to work any issue encountered needs to be reported back :blush:

**Comment by gnull** [comment]
I'm still getting odd errors when trying to run examples with Wayland. I'm doing this from `nix develop` shell with flake.nix at the repo root:

```console
$ cabal run --flags 'examples' -- books
xkbcommon: ERROR: /nix/store/ja09m2gfni7pqk4bsrhjb8y9cq74rspp-libx11-1.8.12/share/X11/locale/en_US.UTF-8/Compose:1661:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /nix/store/ja09m2gfni7pqk4bsrhjb8y9cq74rspp-libx11-1.8.12/share/X11/locale/en_US.UTF-8/Compose:1662:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /nix/store/ja09m2gfni7pqk4bsrhjb8y9cq74rspp-libx11-1.8.12/share/X11/locale/en_US.UTF-8/Compose:1663:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /nix/store/ja09m2gfni7pqk4bsrhjb8y9cq74rspp-libx11-1.8.12/share/X11/locale/en_US.UTF-8/Compose:1664:1: unrecognized keysym "dead_hamza" on left-hand side
xkbcommon: ERROR: /nix/store/ja09m2gfni7pqk4bsrhjb8y9cq74rspp-libx11-1.8.12/share/X11/locale/en_US.UTF-8/Compose:1665:1: unrecognized keysym "dead_hamza" on left-hand side
Invalid window
books: SDLCallFailed {sdlExceptionCaller = "SDL.Video.glCreateContext", sdlFunction = "SDL_GL_CreateContext", sdlExceptionError = "Invalid window"}
```

Adding `SDL_VIDEODRIVER=wayland` has no effect since it seems to be already trying to use Wayland by default. What can I try to make it work?
