### ISSUE TITLE
Rationale: why not optics library?

### ISSUE THREAD

**Issue by Abastro** [fjvallarino/monomer#58]
I see that you took lens rather than microlens for a good reason, but I wonder why you did not choose the optics library - which gives near perfect support with less dependency footprint.

**Comment by fjvallarino** [comment]
Hi! The main reason is that I started this project, in one form or another, in mid-2018 (it was originally an attempt at creating a DAW with a custom UI, which was abandoned for months and resumed several times). At that time I only knew about Lens and MicroLens, and I think Optics was released in late 2019. 

I have not had a strong reason for replacing Lens with Optics. As far as I understand, it's a change that would take quite a bit of effort. You've probably already read it, but I took this article (by one of Optics authors) into consideration when evaluating the benefits of this migration: [Case study: migrating from lens to optics](https://oleg.fi/gists/posts/2020-01-25-case-study-migration-from-lens-to-optics.html).

**Comment by Abastro** [comment]
Oh, I did not know this project had such a long history! Could you include it in the rationale as well? I understand that it is ofc not feasible to migrate this project to optics.

**Comment by fjvallarino** [comment]
Added! https://github.com/fjvallarino/monomer/blob/main/docs/design-decisions.md#why-lens-and-not-optics

**Comment by Abastro** [comment]
Thank you!!!!!!!!!
