### ISSUE TITLE
Config option for setting a minimum thumb size

### ISSUE THREAD

**Issue by simmihugs** [fjvallarino/monomer#61]
I have a problem with scroll scroll_ etc.

In my application I create a vstack with a list of Widgets I create similar to the todo or books example. But my list, based on a xml file I parse is sometimes very large, like 2000 - 3000 items. And sometimes the xml file is shorter hence only 100 - 200 items.

in the case of the very large lists, the thum in the scroll bar becomes very tiny. 

![2022-01-14 18_08_30-Windows PowerShell](https://user-images.githubusercontent.com/51531595/149555119-7588bf8f-ea52-46d7-985d-41550eb5330b.png)

my "solution" was to simply copy the source for Monomer.Widgets.Containers.Scrolll and manually make something like

```
scrollStatus
  :: ScrollCfg s e
  -> WidgetEnv s e
  -> WidgetNode s e
  -> ScrollState
  -> Point
  -> ScrollContext
scrollStatus config wenv node scrollState mousePos = ScrollContext{..} where
...
  hThumbRect = Rect {
    _rX = caLeft - hScrollRatio * dx,
    _rY = caTop + hScrollTop + (barW - thumbW) / 2,
    -- old   _rW = hScrollRatio * vpWidth,
    _rW = minimal $ hScrollRatio * vpWidth,
    _rH = thumbW
  }
  vThumbRect = Rect {
    _rX = caLeft + vScrollLeft + (barW - thumbW) / 2,
    _rY = caTop - vScrollRatio * dy,
    _rW = thumbW,
   -- old _rH = vScrollRatio * vpHeight
    _rH = minimal $ vScrollRatio * vpHeight
  }

minimal x
   | x < 50      = 50
   | otherwise = x
```

**Comment by fjvallarino** [comment]
Hi @simmihugs!

This is an issue on the scroll widget; there is currently no config option for setting a minimum thumb size, and the scroll widget does not have a minimum size for the thumb (but it should).

I'll keep you posted!

**Comment by fjvallarino** [comment]
I just pushed a branch that adds a configuration option to the `scroll` widget, `thumbMinSize`, that allows setting a minimum thumb size; it defaults to 25 pixels.

To use it, you will need to update your `stack.yaml`:
```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: fe94130c385aedf4e6dec1d488fcb8bef26de3a2
```

You could, for example, use it this way:
```haskell
scroll_ [thumbMinSize 200] (image "https://picsum.photos/id/1020/1600/1200")
  `styleBasic` [width 400, height 300]
```

**Comment by fjvallarino** [comment]
The PR has been merged, so the previous commit hash is no longer valid. The new one (which will not be changed or removed) is this:
```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: 187ad94b789ae25830862f53dd9975efc23f8e27
```

**Comment by fjvallarino** [comment]
I'll close this issue since the fix has been merged to master. Please re-open or create a new one if you feel something is missing. Thanks!
