### ISSUE TITLE
DPI calculation discussion

### ISSUE THREAD

**Issue by Kyarigwo** [fjvallarino/monomer#72]
Hi, I've created this item to continue discussion of the DPI issues raised in [https://github.com/fjvallarino/monomer/issues/54](https://github.com/fjvallarino/monomer/issues/54).  

On my machine I have 3 monitors, two are 2560x1440 resolution and one is 1920x1080.  By default the application is opening on one of the 2560x1440 monitors, which is the primary display, however when @fjvallarino mentioned that Platform.hs does some calculations on startup, I tried opening it on my other monitors by setting them as primary.  The other 2560x1440 monitor also has this issue, but the 1920x1080 monitor does not.

**Comment by fjvallarino** [comment]
So, do you still have the disappearing font issue on that other screen? 

I noticed you mentioned this a while ago. What happens if you don't include that argument? Are you including the `-threaded` flag in `package.yaml`?

```
I also need to use the appRenderOnMainThread switch.
```

**Comment by Kyarigwo** [comment]
I don't get it with the fix you provided. 

I do have the -threaded flag in my package.yaml file.  The error I get is:

app: SDLCallFailed {sdlExceptionCaller = "SDL.Video.OpenGL.glMakeCurrent", sdlFunction = "SDL_GL_MakeCurrent", sdlExceptionError = "Unable to make GL context current"}

I see that this is described on [https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md](https://github.com/fjvallarino/monomer/blob/main/docs/tutorials/00-setup.md)  as due to an upstream driver issue, and so I don't think it is an issue, I just mentioned it for completeness.

I think that the difference in text width is something that is going to happen on various system, and so the fix where some tolerance is added is the correct way to handle this.

Anyway, this is a really cool library, and I'm amazed by the amount of work that has gone into it.

**Comment by Dretch** [comment]
In my case, I am running Ubuntu Mate 20.04.3, which uses X11 (Wayland is not supported).

The issue for me is that I have not configured any kind of scaling factor, but because my screens are quite large then Monomer is automatically scaling.

E.g. my laptop screen (17" LG Gram)
```
gareth@gareth-17Z90P-K-AA72A1:~$ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    2560x1600 pixels (677x423 millimeters)
  resolution:    96x96 dots per inch
```

The code in `Platform.hs` / `getLinuxFactor` therefore computes a scaling factor of `2*2560 / 1920 = 2.666...`. This results in the Monomer GUI being massive compared to all the other windows! If I hack Monomer to always use a scaling factor of 1, then the problem goes away.

In general, I suppose the solution would be to use the scaling factor specified by the desktop environment rather than deriving a factor from the pixel-width of the screen. However, this is extremely complicated on Linux (e.g. consider all the different configuration options mentioned on https://wiki.archlinux.org/title/HiDPI)!

**Comment by fjvallarino** [comment]
The initial scale factor handling for Linux can definitely be improved. For Windows, there is some initialization on `dpi.c`. For `macOS`, some weird handling logic is needed (mouse events are not scaled based on DPI on mac, but they are on Linux and Windows).

I think both Mac and Windows work fine in this regard. I'll review the Linux situation; maybe `SDL_GetDisplayDPI` can be used in this case.

**Comment by fjvallarino** [comment]
I looked into adding logic for detecting DPI scaling on Linux, but I did not find the different ideas reliable. Ubuntu seems to do its own thing, and some environment variables may be available or not depending on the window manager. I will keep an eye on whether SDL fixes `SDL_GetDisplayDPI` (it returns zero on Linux) and come back to it in the future.

For the time being, I added a flag called `appDisableAutoScale` that ignores any detected scaling factor.

I also removed the logic of increasingly larger scale factor based on resolution, and settled for 2 as a maximum. While it may be annoying in some cases, I think it is a good default for most users with single monitors.

**Comment by fjvallarino** [comment]
I pushed an extra commit that attempts to use `SDL_GetDisplayDPI` on Linux, since it may work in some cases. If it fails, it will default to the logic mentioned before (assume DPI = 2 if window width > 1920, DPI = 1 otherwise).

**Comment by fjvallarino** [comment]
The improvements to DPI detection and opt-out flag have been merged into main.

There have also been improvements regarding the _"Unable to make GL context current"_ issue. It should no longer be necessary to include `appRenderOnMainThread` as part of the application's configuration; the library will now try to fall back if an error occurs (and it will not attempt to set up threaded rendering if -threaded was not used).

A new release, 1.4.0.0, has been created today including all these changes. I'll close the issue now. Thanks!
