### ISSUE TITLE
SetFocusOnKey misbehaving with textArea

### ISSUE THREAD

**Issue by klausweiss** [fjvallarino/monomer#82]
Hey. First of all, thanks for monomer!

I think `SetFocusOnKey` is not handled as it's supposed to with `textArea`. The widget seems to be focused, but the text is not editable until after I press the tab key.

To illustrate this I've come up with a minimal example (code below). It consists of a `textField` and a `textArea` both modifying the same text. When you switch between them with tab, the text is editable immediately. If you use `C-p` to select the `textArea`, said issue occurs. Selecting `textField` with `C-o` works properly, so I guess the issue lays in `textArea`'s way of handling `SetFocusOnKey`. See the video below:

https://user-images.githubusercontent.com/11031002/153779427-a333aa4f-f020-4f4d-a294-36b5aab7c4d8.mp4

Code to reproduce (note you'll need a font file called `Regular.ttf` in the same folder): 

```haskell
#!/usr/bin/env stack
{- stack 
    script 
    --resolver lts-18.25 
    --package monomer
    --package nanovg
    --package lens
    --package text
    --ghc-options=-threaded
-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

module Main where

import Data.Text
import Control.Lens
import Monomer

newtype AppModel = AppModel { _stateText :: Text }
  deriving (Eq, Show)

data AppEvent
  = FocusTextField
  | FocusTextArea
  deriving (Eq, Show)

makeLenses 'AppModel

buildUI wenv model = widgetTree
 where
  widgetTree =
    keystroke [("C-o", FocusTextField), ("C-p", FocusTextArea)] $
      hstack
        [ textField stateText `nodeKey` "textfield"
        , textArea stateText `nodeKey` "textarea"
        ]

handleEvent wenv node model evt = case evt of
  FocusTextField -> [SetFocusOnKey "textfield"]
  FocusTextArea -> [SetFocusOnKey "textarea"]

main = do
  startApp model handleEvent buildUI config
 where
  config =
    [ appFontDef "Regular" "Regular.ttf"
    , appTheme darkTheme
    ]
  model = AppModel "changing focus with tab"
```

Save the code above as file and simply run with stack
```bash
stack ./Textarea.hs
```

I'm on Linux, if that's of any relevance.

**Comment by fjvallarino** [comment]
Hi @klausweiss! I'm not currently at my computer, but the issue sounds
similar to this one:
https://github.com/fjvallarino/monomer/issues/80. Maybe the same fix
applies in this case too?

**Comment by klausweiss** [comment]
Oh, I looked for textArea in issues before posting, but somehow didn't find the one you mentioned. Yup, that solved the issue. Thanks for prompt response!
