### ISSUE TITLE
Suggestion: add the `forcebreak` option to `labelCfg`

### ISSUE THREAD

**Issue by toku-sa-n** [fjvallarino/monomer#84]
Hi.

Currently `label_` with the `multiline` option only breaks lines at the spaces. Unfortunately, this is not useful for languages that don't use spaces to separate words (e.g., CJK). 

What I'm thinking is to add the `forcebreak` option to `labelCfg`, which allows breaking lines even in the middle of a word. This is not ideal because it ignores the grammatical rule. For example, punctuations may be positioned at the beginning of a line. However, I think considering the rules is difficult.

If adding the `forcebreak` option is acceptable, I'll send a PR (although I may need some help implementing it).

**Comment by fjvallarino** [comment]
Hi!

One option can be adding a new attribute to `TextStyle` that indicates how text should break on multiline. The benefit is that the functionality would be automatically available to all widgets using text (buttons, labeled items, etc.). We can create a new type:
```haskell
data BreakOn
  = BreakOnSpaces
  | BreakOnCharacters
```
Then add:
```haskell
data TextStyle = TextStyle {
  ...
  _txsBreakOn :: Maybe BreakOn
}
```
Additionally, to simplify usage, we can have these combinators (with instances on `TextStyle` and `StyleState`):
```haskell
class CmbBreakOnSpaces where
  ...

class CmbBreakOnCharacters where
  ...
```
Then, in `Monomer.Graphics.Text`'s `fitTextToWidth` (or even `fitLineToW`), we can choose a line breaking function accordingly (maybe defaulting to `BreakOnSpaces`).

Doing this allows for more flexibility to add alternative line-breaking criteria. Do you think adding better CJK line-breaking support is feasible using this model?

**Comment by toku-sa-n** [comment]
Thank you for the detailed explanations! I think `BreakOption` (or `Break`) is better for the type name because we can add, e.g., `BreakForCJK`. I'll implement the `BreakOnCharacters` option and later try the CJK option.

**Comment by fjvallarino** [comment]
Sounds good! Adapt the names as you see fit. The only consideration I would have is, if you export the symbol from the main `Monomer` package, to try not to use a too common word (or maybe add a prefix). I mention something similar in this issue: https://github.com/fjvallarino/monomer/issues/78#issuecomment-1034875486.

**Comment by fjvallarino** [comment]
@toku-sa-n I'll close this issue since the PR was merged. If you feel something is missing, please re-open it or create a new one. Thanks!

**Comment by toku-sa-n** [comment]
No, there are no missing things. Thank you for merging it!
