### ISSUE TITLE
Problem with linking stage in static builds

### ISSUE THREAD

**Issue by sproott** [fjvallarino/monomer#85]
For the past few days, I've been trying to build a static executable of a `monomer` app. I'm now stuck on a linking problem. 

```
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGLU
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGL
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lX11
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lX11
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGLU
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGL
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGLU
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lGL
```

It says basically that GL, GLU and X11 libraries are missing, but they're installed and in `/usr/lib`, so I see no reason why it's failing. Here's a simple repo with the official example and a Dockerfile:

https://github.com/sproott/monomer-static-build-problem

To run the build, do `docker build .`.

**Comment by fjvallarino** [comment]
I honestly don't know what could be happening. This sounds more like an issue caused by what `GHC`/`Stack` expect vs what `Alpine` provides.

There were [some comments](https://www.reddit.com/r/haskell/comments/p12pjs/comment/h8an6c1/?utm_source=reddit&utm_medium=web2x&context=3) about static builds in the announcement post, but it's not something I have investigated.

I'll follow your related [issue](https://github.com/utdemir/ghc-musl/issues/19).

**Comment by sproott** [comment]
Alright, well, from the comments on Reddit, it seems that it's impossible to statically link `GL` and `X11`, so I'll probably just stick to shipping a distro-specific dynamic executable. 

Should I close this issue then?

**Comment by fjvallarino** [comment]
Sure! If you manage to make it work, it would be great to know! 

Thanks!
