### ISSUE TITLE
Bug: shift+drag on TextField widget causes a crash

### ISSUE THREAD

**Issue by Dretch** [fjvallarino/monomer#91]
There seems to be a bug in the TextField because, unlike other InputField types, it does not implement any drag behaviour.

To reproduce, simply hold shift and then click and drag on a TextField -- the program will crash with a `Maybe.fromJust: Nothing` error.

There is a `fromJust` that seems to be the problem, here: https://github.com/fjvallarino/monomer/blob/9f02be85caa5e0e03a1c5c85a28d73b45bf7458b/src/Monomer/Widgets/Singles/Base/InputField.hs#L481

**Comment by fjvallarino** [comment]
It definitely is a bug. I guess I reordered the case branches at some point and missed this case (or it was wrong from the beginning!). Just in case, I added a unit test and validated first that it failed before the fix.

Thanks for reporting!
