### ISSUE TITLE
Question on Producers

### ISSUE THREAD

**Issue by simmihugs** [fjvallarino/monomer#96]
How can I stop Producers and later restart it?
So if a Producer is relevant for some part of the application, which might be inactive / active / inactive ...

How can I access the model from within a producer?
So if a Producer might change its behaviour based on differences in the appmodel, e.g. changes threadDelay

**Comment by fjvallarino** [comment]
There's not a direct way of accessing the model from the producer. I usually apply one of these options:

1. Keep the producer running and ignore the event on the application's event handler during the time you're not interested in it.
2. Create a communication channel (TChan or TQueue) before creating the producer and use it to send messages from the application to the producer (you will need a Task since those channels run in IO). The onInit config option could be useful for creating the channel, or you can even create is before starting Monomer. You can use this to pause the Producer or exit from it (to restart it later).

**Comment by simmihugs** [comment]
Okay, I'm not very familar with the concept, but I think it is kinda what you do in the `ticker` example?

But I guess before I try anything in this direction I first need to learn what a TChan an or TQueue is

Thanks

**Comment by fjvallarino** [comment]
These communication channels can be used for sending messages between threads. A Producer is, in the end, running in a separate thread so a means of communication with the application is needed (the `sendMsg` argument a Producer receives is under the hood a TChan). 

The idea, then, is to have your producer check if it has received a message from the application (`tryReadTChan` is non blocking, while `readTChan` is blocking). The message can be of any type you want, and you will probably use a sum type if you have more than one option. Based on the received message your Producer should act accordingly.

**Comment by Dretch** [comment]
Not sure it is the best way of doing this, but another option is to use a producer that:
1. delays for some time period
2. does some work
3. emits another event that, when handled, will start a new producer to start the loop again at (1)
4. finishes

When the widget is removed from the tree then the event in step 3 is ignored, so the loop stops. There is an example here: https://github.com/Dretch/foundationdb-explorer/blob/ee554bc11050cd04c3e99e9755b9c5264104a988/src/FDBE/Component/Status.hs#L40

The only issue I have noticed is that after the widget is removed from the tree then sometimes  (whenever the widget is replaced with a different kind of composite, I think) monomer emits a message like:
```
("Failed match on Composite handleMessage",StatusEvent)
```
I don't think this is actually an error, though.

**Comment by simmihugs** [comment]
Okay so my solution, just if someone else has this question, is

I create a TChan in main an store it in the `Appmodel`. I use `peekTChan` in my producer and `unGetTChan` in my modifier task

Thanks everyone for the input

```haskell
-- | For TChan stuff
import Control.Applicative
import Control.Monad
import Control.Concurrent
import Control.Concurrent.Chan
import Control.Concurrent.STM.TChan
import GHC.Conc
import System.Random
import Data.Time

main :: IO ()
main = do
  setStdGen $ mkStdGen 42
  queue' <- atomically newTChan
  atomically $ writeTChan queue' 800
  startApp (model queue') handleEvent buildUI config

...

-- producer
producer queue sendMsg = do
  time <- getLocalTimeOfDay
  sendMsg (SetTicker time)
  d <- atomically $ peekTChan queue
  threadDelay $ 1000 * d
  producer queue sendMsg

-- task
task queue' = do
   atomically $ unGetTChan queue' 12
   return AppInit
```
