### ISSUE TITLE
Ubuntu: NVIDIA RTX A6000 - Unable to make GL context current

### ISSUE THREAD

**Issue by MilesLitteral** [fjvallarino/monomer#97]
Hey all, I'm trying to build monomer on Ubuntu and no matter what I do in the build process (stack clean, recloning the repo, reinstalling nvidia drivers) I get this error when trying to run any example apps: 

```
Renderer: NVIDIA RTX A6000/PCIe/SSE2
Version: 3.2.0 NVIDIA 470.103.01
generative: SDLCallFailed {sdlExceptionCaller = "SDL.Video.OpenGL.glMakeCurrent", sdlFunction = "SDL_GL_MakeCurrent", sdlExceptionError = "Unable to make GL context current"}
```

I ran a debug trace(`LD_DEBUG=libs stack run generative`)  which tracked down this error when running stack run generative (for example):

```76922:     /lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01: error: symbol lookup error: undefined symbol: ErrorF (fatal)```

Any help is appreciated I'm at something of a loss

**Comment by fjvallarino** [comment]
There seems to be a driver issue with some cards on Linux. Check [this issue](https://github.com/fjvallarino/monomer/issues/83). There's a configuration flag at the bottom that may help you.

**Comment by MilesLitteral** [comment]
I looked through the referenced issue and implemented what solution I could to no avail; for now it seems like a now Known Issue, I appreciate all your help 🙏🏽

**Comment by fjvallarino** [comment]
Sorry, I answerer from my phone and I pasted the wrong issue. I meant to paste this one: https://github.com/fjvallarino/monomer/issues/9. 

I think if you add `appRenderOnMainThread` to the configuration options list provided to `startApp` the issue should go away.

**Comment by fjvallarino** [comment]
For instance, in the Generative example, the code would be:

```haskell

main :: IO ()
main = do
  startApp model handleEvent buildUI config
  where
    model = GenerativeModel CirclesGrid False def def
    config = [
      appWindowTitle "Generative",
      appWindowIcon "./assets/images/icon.bmp",
      appTheme darkTheme,
      appFontDef "Remix" "./assets/fonts/remixicon.ttf",
      appFontDef "Regular" "./assets/fonts/Roboto-Regular.ttf",
      appInitEvent GenerativeInit,
      -- Extra flag
      appRenderOnMainThread
      ]

```

**Comment by MilesLitteral** [comment]
That worked like a charm! 
Thank you very much :)

**Comment by fjvallarino** [comment]
Great! I'll close the issue, then.
